version: 2

vm_settings: &vm_settings
  docker:
    # https://circleci.com/docs/2.0/circleci-images/#nodejs
    - image: circleci/node:latest-browsers
  working_directory: ~/app

install_restore_cache: &install_restore_cache
  name: Restore cached dependencies
  keys:
    - dependencies-{{ checksum "yarn.lock" }}
    # Fall back to using the latest cache if no exact match is found
    - dependencies

install_run: &install_run
  name: Install dependencies with Yarn, purely from the lockfile
  command: yarn install

install_save_cache: &install_save_cache
  name: Cache installed dependencies
  paths:
    - ~/.cache
  key: dependencies-{{ checksum "yarn.lock" }}

jobs:
  test:
    <<: *vm_settings
    steps:
      - checkout

      # Install dependencies
      - restore_cache: *install_restore_cache
      - run: *install_run
      - save_cache: *install_save_cache

      #- run:
      #    name: Run Unit Tests
      #    command: yarn test:unit

      - run:
          name: Run e2e Tests
          # Install libgconf, needed by Cypress' Electron, then run tests
          command: sudo apt-get install libgconf-2-4 && yarn test:e2e

      # Store test artifacts
      #- store_artifacts:
      #    path: tests/unit/coverage
      - store_artifacts:
          path: tests/e2e/videos
      - store_artifacts:
          path: tests/e2e/screenshots

  build:
    <<: *vm_settings
    steps:
      - checkout

      # Install dependencies
      - restore_cache: *install_restore_cache
      - run: *install_run
      - save_cache: *install_save_cache

      - run:
          name: Build for production
          command: yarn build

      - persist_to_workspace:
          root: /home/circleci/app
          paths: dist

  deploy:
    <<: *vm_settings
    steps:
      - checkout

      # Install dependencies
      - restore_cache: *install_restore_cache
      - run: *install_run

      - attach_workspace:
          at: /home/circleci/app/dist

      - run:
          name: Install gh-pages
          command: sudo npm install -g gh-pages gh-pages-deploy
      - run:
          name: Configure git
          command: |
            git config user.email "dereckmartin@github.com"
            git config user.name "Dereck Martin"
      - run:
          name: Deploy docks to gh-pages branch
          command: |
            git branch --delete --force gh-pages
            git checkout --orphan gh-pages
            git add -f dist
            git commit -m "Rebuild gh-pages [ci skip]"
            git filter-branch -f --prune-empty --subdirectory-filter dist
            git push -f origin gh-pages

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
      - build:
          requires:
            - test
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

