version: 2

vm_settings: &vm_settings
  docker:
    # https://circleci.com/docs/2.0/circleci-images/#nodejs
    - image: circleci/node:latest-browsers
  working_directory: ~/app

install_restore_cache: &install_restore_cache
  name: Restore cached dependencies
  keys:
    - dependencies-{{ checksum "yarn.lock" }}
    # Fall back to using the latest cache if no exact match is found
    - dependencies

install_run: &install_run
  name: Install dependencies with Yarn, purely from the lockfile
  command: yarn install --frozen-lockfile

install_save_cache: &install_save_cache
  name: Cache installed dependencies
  paths:
    - ~/.cache
  key: dependencies-{{ checksum "yarn.lock" }}

jobs:
  test:
    <<: *vm_settings
    steps:
      - checkout

      # Install dependencies
      - restore_cache: *install_restore_cache
      - run: *install_run
      - save_cache: *install_save_cache

      - run:
          name: Run tests
          # Install libgconf, needed by Cypress' Electron, then run tests
          command: sudo apt-get install libgconf-2-4 && yarn test:ci

      # Store test artifacts
      - store_artifacts:
          path: tests/unit/coverage
      - store_artifacts:
          path: tests/e2e/videos
      - store_artifacts:
          path: tests/e2e/screenshots

  build:
    <<: *vm_settings
    steps:
      - checkout

      # Install dependencies
      - restore_cache: *install_restore_cache
      - run: *install_run
      - save_cache: *install_save_cache

      - run:
          name: Build for production
          command: yarn build:ci

      - persist_to_workspace:
          root: /home/circleci/app
          paths: dist

  deploy:
    <<: *vm_settings
    steps:
      - add_ssh_keys:
          fingerprints:
            - "02:3d:a1:64:e8:7b:2b:d9:32:45:ff:0b:e9:52:41:07"
      - checkout

      # Install dependencies
      - restore_cache: *install_restore_cache
      - run: *install_run

      - attach_workspace:
          at: /home/circleci/app/dist

      - run:
          name: Install gh-pages
          command: sudo npm install -g gh-pages
      - run:
          name: Configure git
          command: |
            git config user.email "dereckmartin@github.com"
            git config user.name "Dereck Martin"
      - run:
          name: Deploy docks to gh-pages branch
          command: gh-pages --dist dist --src "**" --dest .

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

